default['php']['secure_functions']['disable_functions'] = ''
default["php"]["apc"]["local_size"] = "128M"
default["php"]["apc"]["shm_size"] = "256M"
default["php"]["apc"]["ttl"] = "3600"
default["php"]["apc"]["user_ttl"] = "3600"
default['php']['ini_settings'] = {
        'short_open_tag' => 'On',
        'open_basedir' => '',
        'max_execution_time' => '7200',
        'max_input_time' => '7200',
        'memory_limit' => '-1',
        'post_max_size' => '200M',
        'upload_max_filesize' => '200M',
        'max_file_uploads' => '100'
        'error_reporting' => 'E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED',
        'error_log' => '',
        'allow_url_fopen' => 'On',
        'date.timezone' => 'Europe/Brussels',
        'date.default_latitude' => '50.877369',
        'date.default_longitude' => '4.684167',
        'session.cookie_secure' => '0',
        'session.cookie_httponly' => '1',
        'session.gc_probability' => '1',
        'session.gc_divisor' => '100',
        'session.gc_maxlifetime' => '1400',
        'xdebug.max_nesting_level' => '1000'
}
